name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest,]
        include: 
        - os: windows-latest        
        - os: ubuntu-latest         
    steps:
     - uses: actions/checkout@v1
     - run: echo ${{matrix.TARGET}}
