name: Windows CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Echo
      run: echo "$HOME"
    - name: Echo
      run: echo "$GITHUB_WORKFLOW"
    - name: Echo
      run: echo "$GITHUB_RUN_ID"
    - name: Echo
      run: echo "$GITHUB_RUN_NUMBER"
    - name: Echo
      run: echo "$GITHUB_ACTION"
    - name: Echo
      run: echo "$GITHUB_ACTIONS"
    - name: Echo
      run: echo "$GITHUB_ACTOR"
    - name: Echo
      run: echo "$GITHUB_REPOSITORY"
    - name: Echo
      run: echo "$GITHUB_EVENT_NAME"
    - name: Echo
      run: echo "$GITHUB_EVENT_PATH"
    - name: Echo
      run: echo "$GITHUB_WORKSPACE"
    - name: Echo
      run: echo "$GITHUB_SHA"
    - name: Echo
      run: echo "$GITHUB_REF"
    - name: Echo
      run: echo "$GITHUB_HEAD_REF"
    - name: Echo
      run: echo "$GITHUB_BASE_REF"

    - name: MSBuild
      working-directory: src
      run: msbuild LogitechAudioVisualizer\LogitechAudioVisualizer.sln
      
#name: Windows

#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [windows-latest]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1.4.0
#      with:
#        dotnet-version: 3.1.101
#
#    - name: Build with dotnet
#      run: dotnet build --configuration Release
      
#name: Ubuntu
#
#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1.4.0
#      with:
#        dotnet-version: 3.1.101
#
#    - name: Build with dotnet
#      run: dotnet build --configuration Release
#
