name: Windows CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

   # - name: Setup MSBuild.exe
   #   uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Restore
      run: nuget restore $Env:GITHUB_WORKSPACE\LogitechAudioVisualizer.sln  
    
    - name: Build Logitech Audio Visualizer
      run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\LogitechAudioVisualizer.sln  

    #- name: MSBuild
    #  working-directory: "D:\a\LogitechAudioVisualizer\LogitechAudioVisualizer"
    #  run: msbuild LogitechAudioVisualizer.sln
      
#name: Windows

#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [windows-latest]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1.4.0
#      with:
#        dotnet-version: 3.1.101
#
#    - name: Build with dotnet
#      run: dotnet build --configuration Release
      
#name: Ubuntu
#
#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1.4.0
#      with:
#        dotnet-version: 3.1.101
#
#    - name: Build with dotnet
#      run: dotnet build --configuration Release
#
